name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGION: "cn-east-3"
  ORG: "zxy2023112454"
  BACKEND_IMAGE: swr.cn-east-3.myhuaweicloud.com/${{ env.ORG }}/backend
  FRONTEND_IMAGE: swr.cn-east-3.myhuaweicloud.com/${{ env.ORG }}/frontend
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Login to Huawei Cloud SWR
        run: |
          docker login -u ${{ secrets.SWR_REGION }}@${{ secrets.SWR_ACCESS_KEY }} -p ${{ secrets.SWR_SECRET_KEY }} swr.${{ secrets.SWR_REGION }}.myhuaweicloud.com
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:${{ env.TAG }}
          platforms: linux/amd64
          provenance: false

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:${{ env.TAG }}
          platforms: linux/amd64
          provenance: false

  update-deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update backend image
        uses: bitovi/github-actions-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          kubectl_version: '1.35'
          args: set image deployment/backend backend=${{ env.BACKEND_IMAGE }}:${{ env.TAG }} -n default

      - name: Update frontend image
        uses: bitovi/github-actions-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: set image deployment/frontend frontend=${{ env.FRONTEND_IMAGE }}:${{ env.TAG }} -n default

      - name: Check rollout status
        uses: bitovi/github-actions-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: rollout status deployment/backend -n default